[package]
name = "vtm-voxelize"
version.workspace = true
authors.workspace = true
license.workspace = true
edition = "2024"

[dependencies]
voxelis.workspace = true

[features]
memory_stats = ["voxelis/memory_stats"]
